name: linux

on:
  push:
    branches:
    - build-test-hardware

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [
          blacksmith-2vcpu-ubuntu-2204,
          blacksmith-2vcpu-ubuntu-2204,
          blacksmith-2vcpu-ubuntu-2204,
          blacksmith-2vcpu-ubuntu-2204,
          blacksmith-2vcpu-ubuntu-2204,
          blacksmith-2vcpu-ubuntu-2204,
          blacksmith-2vcpu-ubuntu-2204
        ]
    name: ${{matrix.runs-on}}
    runs-on: ${{matrix.runs-on}}
    continue-on-error: true

    steps:
    - name: "Provider: AWS Metadata"
      continue-on-error: true
      run: curl -s --connect-timeout 2 http://169.254.169.254/latest/meta-data/

    - name: "Provider: Cloud Init Info"
      continue-on-error: true
      run: cloud-init query --all 2>/dev/null || cat /etc/cloud/cloud.cfg.d/*.cfg 2>/dev/null || echo "No cloud-init info available"
    
    - name: "Provider Info"
      continue-on-error: true
      run: |
        curl -s ipinfo.io