name: linux

on:
  push:
    branches:
    - build-test-2

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [
          # ubuntu-22.04, ubuntu-24.04,
          # ubicloud-standard-2-ubuntu-2204, ubicloud-standard-2-ubuntu-2404,
          # ubicloud-standard-2-arm-ubuntu-2204, ubicloud-standard-4-arm-ubuntu-2204,
          # buildjet-2vcpu-ubuntu-2204, buildjet-2vcpu-ubuntu-2404,
          # buildjet-2vcpu-ubuntu-2204-arm, buildjet-4vcpu-ubuntu-2204-arm,
          # namespace-profile-x64-2x8,
          # namespace-profile-arm64-2x8, namespace-profile-arm64-4x16,
          # warp-ubuntu-latest-x64-2x, warp-ubuntu-2204-x64-2x,
          # warp-ubuntu-2204-arm64-2x, warp-ubuntu-2204-arm64-4x,
          # blacksmith-2vcpu-ubuntu-2204, blacksmith-4vcpu-ubuntu-2204,
          # blacksmith-2vcpu-ubuntu-2204-arm, blacksmith-4vcpu-ubuntu-2204-arm,
          # blacksmith-2vcpu-ubuntu-2204, blacksmith-2vcpu-ubuntu-2404
          ubuntu-24.04,
          ubicloud-standard-2-ubuntu-2404,
          # ubicloud-premium-8-ubuntu-2404,
          # buildjet-8vcpu-ubuntu-2404,
          blacksmith-2vcpu-ubuntu-2404,
          warp-ubuntu-2404-x64-2x
        ]
    name: ${{matrix.runs-on}}
    runs-on: ${{matrix.runs-on}}
    continue-on-error: true

    steps:
    - uses: actions/checkout@v6

    - name: check apt mirrors files
      run: sudo cat /etc/apt/apt-mirrors.txt

    - name: check apt sources list
      run: sudo cat /etc/apt/sources.list

    - name: check apt sources list.d
      run: sudo ls -l /etc/apt/sources.list.d

    - name: check ubuntu sources
      run: sudo cat /etc/apt/sources.list.d/ubuntu.sources || true
    
    - run: sudo apt-get update