name: Benchmark cache
on:
  push:
    branches:
      - cache-test

jobs:
  save_cache:
    name: ${{ matrix.runner }} to ${{ matrix.cache-provider }}
    strategy:
      matrix:
        index: [1,2,3,4,5,6,7,8,9,10]
        runner: [ubicloud, ubuntu-latest]
        cache-provider: [github, ubicloud]
        exclude:
          - runner: ubuntu-latest
            cache-provider: ubicloud
 
    runs-on: ${{ matrix.runner }}
    steps:
      - run: sleep 10
      - name: ubicloud/cache@v4
        if: matrix.cache-provider == 'ubicloud'
        id: cache-ubicloud
        uses: ubicloud/cache@v4
        with:
          path: 500mb-file 
          key: 500mb-${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.runner }}-${{ matrix.index }}

      - name: actions/cache@v4
        if: matrix.cache-provider == 'github'
        id: cache-github
        uses: actions/cache@v4
        with:
          path: 500mb-file 
          key: 500mb-${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.runner }}-${{ matrix.index }}
  
      - name: Generate test file if cache miss
        if: steps.cache-ubicloud.outputs.cache-hit != 'true' && steps.cache-github.outputs.cache-hit != 'true'
        run: dd if=/dev/urandom of=500mb-file bs=1M count=500

      - name: Verify file
        run: | 
          ls -lah 500mb-file
          sha256sum 500mb-file

  restore_cache:
    name: ${{ matrix.runner }} from ${{ matrix.cache-provider }}
    needs: save_cache
    strategy:
      matrix:
        index: [1,2,3,4,5,6,7,8,9,10]
        runner: [ubicloud, ubuntu-latest]
        cache-provider: [github, ubicloud]
        exclude:
          - runner: ubuntu-latest
            cache-provider: ubicloud

    runs-on: ${{ matrix.runner }}
    steps:
      - run: sleep 10
      - name: ubicloud/cache@v4
        if: matrix.cache-provider == 'ubicloud'
        id: cache-ubicloud
        uses: ubicloud/cache@v4
        with:
          path: 500mb-file 
          key: 500mb-${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.runner }}-1

      - name: actions/cache@v4
        if: matrix.cache-provider == 'github'
        id: cache-github
        uses: actions/cache@v4
        with:
          path: 500mb-file 
          key: 500mb-${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.runner }}-1

      - name: Check cache exists
        continue-on-error: true
        if: steps.cache-ubicloud.outputs.cache-hit != 'true' && steps.cache-github.outputs.cache-hit != 'true'
        run: exit 1

      - name: Verify file
        continue-on-error: true
        run: | 
          ls -lah 500mb-file
          sha256sum 500mb-file

    