name: Benchmark cache
on:
  push:
    branches:
      - cache-test

jobs:
  save_cache:
    name: ${{ matrix.runner }} save ${{ matrix.index }} 
    strategy:
      matrix:
        index: [1,2,3,4,5]
        runner: [ubicloud, ubuntu-latest, buildjet-2vcpu-ubuntu-2204, blacksmith-2vcpu-ubuntu-2204]
        # cache-provider: [github, ubicloud, buildjet-2vcpu-ubuntu-2204]
 
    runs-on: ${{ matrix.runner }}
    steps:
      - run: sleep 5

      - name: ubicloud/cache@v4
        if: matrix.runner == 'ubicloud'
        id: cache-ubicloud
        uses: ubicloud/cache@v4
        with:
          path: 500mb-file 
          key: 500mb-${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.runner }}-${{ matrix.index }}

      - name: actions/cache@v4
        if: matrix.runner == 'ubuntu-latest'
        id: cache-github
        uses: actions/cache@v4
        with:
          path: 500mb-file 
          key: 500mb-${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.runner }}-${{ matrix.index }}
 
      - name: buildjet/cache@v4
        if: matrix.runner == 'buildjet-2vcpu-ubuntu-2204'
        id: cache-buildjet
        uses: buildjet/cache@v4
        with:
          path: 500mb-file 
          key: 500mb-${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.runner }}-${{ matrix.index }}
 
      - name: useblacksmith/cache@v5
        if: matrix.runner == 'blacksmith-2vcpu-ubuntu-2204'
        id: cache-blacksmith
        uses: useblacksmith/cache@v5
        with:
          path: 500mb-file 
          key: 500mb-${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.runner }}-${{ matrix.index }}
  
      - name: Generate test file if cache miss
        if: steps.cache-ubicloud.outputs.cache-hit != 'true' && steps.cache-github.outputs.cache-hit != 'true'  && steps.cache-buildjet.outputs.cache-hit != 'true' && steps.cache-blacksmith.outputs.cache-hit != 'true'
        run: dd if=/dev/urandom of=500mb-file bs=1M count=500

      - name: Verify file
        run: | 
          ls -lah 500mb-file
          sha256sum 500mb-file

  restore_cache:
    name: ${{ matrix.runner }} restore ${{ matrix.index }} 
    needs: save_cache
    strategy:
      matrix:
        index: [1,2,3,4,5]
        runner: [ubicloud, buildjet-2vcpu-ubuntu-2204, blacksmith-2vcpu-ubuntu-2204]

    runs-on: ${{ matrix.runner }}
    steps:
      - run: sleep 5

      - name: ubicloud/cache@v4
        if: matrix.runner == 'ubicloud'
        id: cache-ubicloud
        uses: ubicloud/cache@v4
        with:
          path: 500mb-file 
          key: 500mb-${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.runner }}-1

      - name: actions/cache@v4
        if: matrix.runner == 'ubuntu-latest'
        id: cache-github
        uses: actions/cache@v4
        with:
          path: 500mb-file 
          key: 500mb-${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.runner }}-1

      - name: buildjet/cache@v4
        if: matrix.runner == 'buildjet-2vcpu-ubuntu-2204'
        id: cache-buildjet
        uses: buildjet/cache@v4
        with:
          path: 500mb-file 
          key: 500mb-${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.runner }}-1

      - name: useblacksmith/cache@v5
        if: matrix.runner == 'blacksmith-2vcpu-ubuntu-2204'
        id: cache-blacksmith
        uses: useblacksmith/cache@v5
        with:
          path: 500mb-file 
          key: 500mb-${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.runner }}-1
 
      - name: Check cache exists
        continue-on-error: true
        if: steps.cache-ubicloud.outputs.cache-hit != 'true' && steps.cache-github.outputs.cache-hit != 'true'  && steps.cache-buildjet.outputs.cache-hit != 'true' && steps.cache-blacksmith.outputs.cache-hit != 'true'
        run: exit 1

      - name: Verify file
        continue-on-error: true
        run: | 
          ls -lah 500mb-file
          sha256sum 500mb-file

    